### ISSUE TITLE
Object Snapping

### ISSUE THREAD

**Issue by cade9522** [TheVindicators/Vis#15]
Create functionality for snapping objects together

**Comment by davidlohle** [comment]
Hey @nitgarg99 any progress on this?

**Comment by nitgarg99** [comment]
I'm having trouble getting it to work. I committed what I have so far on my branch. I think I'm close but I don't know what's wrong.

https://github.com/TheVindicators/Vis/commit/09aac1f228ae05e3636fcc7ebc95287206c4bd58

**Comment by davidlohle** [comment]
Just to clarify, did #61 fully implement this issue? Can we close this?

**Comment by nitgarg99** [comment]
Yah its fully implemented
