### ISSUE TITLE
Wire Frame Bug

### ISSUE THREAD

**Issue by jwaney** [TheVindicators/Vis#30]
We need help fixing a bug with our wire frame implementation. Currently once you select an object you can click a checkbox to turn the objects wire frame on and off, however, when you leave deselect the object or change selected objects the checkbox's value does not change. So I need someone to add a way for the program to check the status of the current selected object, is it wire frame or not, and change the check box accordingly.

**Comment by davidlohle** [comment]
Fixed by 49723c6
